<div id="top-slide-outer-wrapper">
	<div id="top-slide-inner-wrapper">
		<div id="slide-6" class="slide-wrapper">
			<div class="slide-container">
				<?php foreach ($this->slides AS $s):?>
				<div class="slide-desc">
					<?php echo $s['content']; ?>
				</div><!-- .slide-desc -->
				<?php endforeach; ?>
			</div><!-- .slide-container -->
		</div><!-- #slide-6 -->
	</div>
</div>
<script>
//<![CDATA[
	$("#slide-6").mbSlider({
		animPause	: <?php echo $this->slides[0]['animPause']; ?>,
		animDur		: <?php echo $this->slides[0]['animDur']; ?>,
		animTypeD	: "<?php echo $this->slides[0]['animTypeD']; ?>"
	});
//]]>
</script>