<h3 class="content-title"><?php echo $this->title; ?></h3>
<?php echo $this->translate('delete_section_confirm_msg'); ?><br /><br />

<b><?php echo $this->translate('are_you_sure'); ?></b><br /><br />

<a class="bs-link-button" href="<?php echo $this->url(); ?>/confirm/no"><?php echo $this->translate('no'); ?></a> 
<a class="bs-link-button" href="<?php echo $this->url(); ?>/confirm/yes"><?php echo $this->translate('yes'); ?></a>