<tr>
	<td><?php echo $this->man_id; ?>.</td>
	<td><?php echo $this->man_name; ?></td>
	<td class="link-v2 w15">
		<a class="bs-link-v2 edit" href="/admin/manufacturer/edit/id/<?php echo $this->man_id; ?>"><?php echo $this->translate('edit')?></a>
		<a class="bs-link-v2 delete" href="/admin/manufacturer/delete/id/<?php echo $this->man_id; ?>"><?php echo $this->translate('delete')?></a>
	</td>
	<td><?php echo $this->man_code; ?></td>
	<td><?php echo $this->shortText($this->man_description); ?></td>
	<td><?php echo $this->man_tags; ?></td>
	<td><?php echo $this->translate($this->man_publish); ?></td>
</tr>
<tr><td colspan="8" style="padding:0px;"><div class="border-dotted"></div></td></tr>