<tr>
	<td><?php echo $this->sec_id; ?>.</td>
	<td><?php echo $this->sec_name; ?></td>
	<td class="link-v2 w15">
		<a class="bs-link-v2 edit" href="/admin/section/edit/id/<?php echo $this->sec_id; ?>"><?php echo $this->translate('edit')?></a>
		<a class="bs-link-v2 delete" href="/admin/section/delete/id/<?php echo $this->sec_id; ?>"><?php echo $this->translate('delete')?></a>
	</td>
	<td><?php echo $this->sec_code; ?></td>
	<td><?php echo $this->shortText($this->sec_description); ?></td>
	<td><?php echo $this->sec_tags; ?></td>
	<td><?php echo $this->translate($this->sec_publish); ?></td>
</tr>
<tr><td colspan="8" style="padding:0px;"><div class="border-dotted"></div></td></tr>