<tr>
	<td><?php echo $this->order; ?></td>
	<td class="link-v2 w15">
		<a class="bs-link-v2 edit" href="/admin/slide/edit/id/<?php echo $this->id; ?>"><?php echo $this->translate('edit')?></a>
		<a class="bs-link-v2 delete" href="/admin/slide/delete/id/<?php echo $this->id; ?>"><?php echo $this->translate('delete')?></a>
	</td>
	<td><?php echo $this->start; ?></td>
	<td><?php echo $this->end; ?></td>
	<td><?php echo $this->group_name; ?></td>
</tr>
<tr><td colspan="14" style="padding:0px;"><div class="border-dotted"></div></td></tr>