<?php if ($this->pageCount) : ?>
<div class="paginationControl">
<?php if (isset($this->previous)) : ?>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>"><?php echo $this->translate('first'); ?></a>
<?php else : ?>
  <span class="disabled"><?php echo $this->translate('first'); ?></span>
<?php endif; ?>

<?php if (isset($this->previous)) : ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; <?php echo $this->translate('previous'); ?></a>
<?php else : ?>
  <span class="disabled">&lt; <?php echo $this->translate('previous'); ?></span>
<?php endif; ?>

<?php foreach ($this->pagesInRange as $page) : ?>
	<?php if ($page != $this->current) : ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
	<?php else : ?>
    <span class="current"><?php echo $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>

<?php if (isset($this->next)) : ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>"><?php echo $this->translate('next'); ?> &gt;</a>
<?php else : ?>
  <span class="disabled"><?php echo $this->translate('next'); ?> &gt;</span>
<?php endif; ?>

<?php if (isset($this->next)) : ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>"><?php echo $this->translate('last'); ?></a> 
<?php else : ?>
  <span class="disabled"><?php echo $this->translate('last'); ?></span> 
<?php endif; ?>
</div>
<?php endif; ?>