<h3 class="content-title"><?php echo $this->title; ?></h3>
<?php echo $this->flashMessenger(); ?>

<div id="bs-grid">
<div class="pagination">
<?php if (count($this->paginator)) : 
  echo $this->paginationControl($this->paginator, 'Sliding', '_paginationControl.phtml');
endif; ?>
</div>
<table class="bs-grid-table">
	<tr>
		<th><?php echo $this->translate('image')?></th>
		<th colspan="2"><?php echo $this->translate('name')?></th>
		<th><?php echo $this->translate('price')?></th>
		<!-- <th><?php //echo $this->translate('description')?></th> -->
		<th><?php echo $this->translate('tags')?></th>
		<th><?php echo $this->translate('publish')?></th>
		<th><?php echo $this->translate('code')?></th>
		<th><?php echo $this->translate('stock')?></th>
		<th><?php echo $this->translate('category')?></th>
		<th><?php echo $this->translate('section')?></th>
		<th><?php echo $this->translate('manufaturer')?></th>
		<th><?php echo $this->translate('start')?></th>
		<th><?php echo $this->translate('expiration')?></th>
	</tr>
<?php if (count($this->paginator)) : 
  echo $this->partialLoop('_partials/_featured-list.phtml', $this->paginator);
endif; ?>
</table>
</div>